export interface ComponentNode {
  id: string;
  name: string;
  description: string;
  x: number;
  y: number;
  width: number;
  height: number;
  createdAt: number;
  updatedAt: number;
  /** Freeform notes about intent, states, interactions — read by the agent when it builds this sketch. */
  notes?: string;
  /** 'sketch' = an idea placed on the canvas, not yet built. 'built' = a real file exists in the repo. */
  status?: 'sketch' | 'built';
  /** Path (relative to the repo root) of the real component file, once built. */
  builtFilePath?: string;
  /**
   * Self-contained React/TSX source for a live preview, written by the coding agent
   * (not generated by Klose). Rendered in a sandboxed iframe — see components/Runtime/Preview.tsx.
   * This is a visualization aid, not the real component; the real file (once built) lives
   * in the project's actual source tree at builtFilePath.
   */
  code?: string;
  /** Freeform feedback on this sketch — left by the user, read (and clearable) by the agent. */
  comments?: Comment[];
}

export interface Comment {
  id: string;
  text: string;
  createdAt: number;
  /** When set, this comment targets a specific element inside the sketch's live preview. */
  element?: SelectedElementInfo;
}

/** A DOM element picked from a sketch's live preview, used to scope a comment to it. */
export interface SelectedElementInfo {
  tagName: string;
  /** Trimmed visible text of the element (truncated). */
  text: string;
  /** The element's class attribute (its Tailwind classes) — helps the agent locate it. */
  classes: string;
  /** Short ancestor breadcrumb of tag names, e.g. "div > div > button". */
  path: string;
}

/** A prop pulled from a component's `NameProps` interface/type by the scanner. */
export interface ComponentProp {
  name: string;
  type: string;
  optional: boolean;
}

/** A real component discovered in the host repo by the server-side scanner. */
export interface RepoComponent {
  /** Stable id: `<file>#<name>`. */
  id: string;
  name: string;
  /** Repo-relative path of the file it's declared in. */
  file: string;
  /** Repo-relative path without extension — what a consumer would import. */
  importPath: string;
  line: number;
  isDefaultExport: boolean;
  description: string;
  props: ComponentProp[];
  /** Grouping label derived from the file's folder (e.g. "ui", "Layout"). */
  category: string;
  loc?: number;
}

export interface ComponentIndex {
  root: string;
  scannedAt: string;
  filesScanned: number;
  truncated: boolean;
  count: number;
  components: RepoComponent[];
}

export interface CanvasState {
  width: number;
  height: number;
  offsetX: number;
  offsetY: number;
}

export interface DragState {
  isDragging: boolean;
  nodeId: string | null;
  startX: number;
  startY: number;
  initialNodeX: number;
  initialNodeY: number;
}

export interface ResizeState {
  isResizing: boolean;
  nodeId: string | null;
  handle: 'nw' | 'ne' | 'sw' | 'se' | 'n' | 'e' | 's' | 'w' | null;
  startX: number;
  startY: number;
  initialX: number;
  initialY: number;
  initialWidth: number;
  initialHeight: number;
}

export type ThemeMode = 'dark' | 'light';

export interface ProjectContext {
  projectDescription: string;
  targetAudience: string;
  brandName: string;
  brandVoice: string;
  designReferences: string;
  techNotes: string;
  productInfo: string;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  nodes: ComponentNode[];
  created_at: string;
  updated_at: string;
  /** Freeform notes about the project's design system (tokens, references, conventions) — read by the agent, not consumed by Klose itself. */
  designSystemPrompt?: string;
  projectContext?: ProjectContext;
}

export interface UserSettings {
  themeMode: ThemeMode;
  cssLogicalProperties: boolean;
  rtlDirection: boolean;
}
