export interface ComponentNode {
  id: string;
  name: string;
  description: string;
  x: number;
  y: number;
  width: number;
  height: number;
  createdAt: number;
  updatedAt: number;
  /** Freeform notes about intent, states, interactions — read by the agent when it builds this sketch. */
  notes?: string;
  /** 'sketch' = an idea placed on the canvas, not yet built. 'built' = a real file exists in the repo. */
  status?: 'sketch' | 'built';
  /** Path (relative to the repo root) of the real component file, once built. */
  builtFilePath?: string;
  /** For a node pulled from a real repo component: which export in `code` to render. */
  exportName?: string;
  /**
   * Self-contained React/TSX source for a live preview, written by the coding agent
   * (not generated by Klose). Rendered in a sandboxed iframe — see components/Runtime/Preview.tsx.
   * This is a visualization aid, not the real component; the real file (once built) lives
   * in the project's actual source tree at builtFilePath.
   */
  code?: string;
  /** Freeform feedback on this sketch — left by the user, read (and clearable) by the agent. */
  comments?: Comment[];
  /** What Jev said this sketch is, once classified (server/classify.js). */
  classification?: SketchClassification;
}

/** Jev's answer about a sketch: its role and kind, and the repo primitives it looks like a copy of. */
export interface SketchClassification {
  role: ComponentRole;
  kind: ComponentKind;
  roleConfidence?: number | null;
  kindConfidence?: number | null;
  /** Classified primitives of the repo with the same kind, when the sketch is itself a primitive. */
  overlaps?: { id: string; name: string; file: string }[];
  /** Hash of what was sent; a changed name, description or notes asks again. */
  key?: string;
  model?: string;
  at?: string;
}

export type TriageKind = 'copy' | 'visual' | 'layout' | 'behaviour' | 'scope';
export type TriageEffort = 'quick' | 'moderate' | 'rethink';

/** Jev's triage of a comment (server/triage.js): what it asks for, and how much work it is. */
export interface CommentTriage {
  kind: TriageKind;
  effort: TriageEffort;
  kindConfidence?: number | null;
  effortConfidence?: number | null;
  key?: string;
  model?: string;
  at?: string;
}

export interface Comment {
  id: string;
  text: string;
  createdAt: number;
  /** When set, this comment targets a specific element inside the sketch's live preview. */
  element?: SelectedElementInfo;
  /** When the canvas last copied this comment for the agent. Unset = new. */
  sentAt?: number;
  /** When the comment was marked addressed (by the agent via `klose resolve`, or by the user). */
  resolvedAt?: number;
  /** What the agent said it changed, when it resolved the comment. */
  resolution?: string;
  /** Jev's triage, once asked for. */
  triage?: CommentTriage;
}

/** A DOM element picked from a sketch's live preview, used to scope a comment to it. */
export interface SelectedElementInfo {
  tagName: string;
  /** Trimmed visible text of the element (truncated). */
  text: string;
  /** The element's class attribute (its Tailwind classes) — helps the agent locate it. */
  classes: string;
  /** Short ancestor breadcrumb of tag names, e.g. "div > div > button". */
  path: string;
  /**
   * nth-child path from the preview root, e.g. "1>3>2" — lets the canvas put
   * the comment's pin back on this exact element. Absent on older comments.
   */
  locator?: string;
}

/** Where a commented element sits inside its sketch's preview, in preview pixels. */
export interface PinPosition {
  /** The comment id (or "draft" for the element picked for the next comment). */
  id: string;
  found: boolean;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
}

/** A prop pulled from a component's `NameProps` interface/type by the scanner. */
export interface ComponentProp {
  name: string;
  type: string;
  optional: boolean;
}

/** A real component discovered in the host repo by the server-side scanner. */
export interface RepoComponent {
  /** Stable id: `<file>#<name>`. */
  id: string;
  name: string;
  /** Repo-relative path of the file it's declared in. */
  file: string;
  /** Repo-relative path without extension — what a consumer would import. */
  importPath: string;
  line: number;
  isDefaultExport: boolean;
  description: string;
  props: ComponentProp[];
  /** Grouping label derived from the file's folder (e.g. "ui", "Layout"). */
  category: string;
  loc?: number;
  /** True when the file has no repo-local (relative) imports, so it can render in the sandbox. */
  previewable?: boolean;
  /** What Jev said it is, once classified (server/classify.js). */
  role?: ComponentRole;
  kind?: ComponentKind;
  roleConfidence?: number | null;
  kindConfidence?: number | null;
  /** 0–1 fit for a search by meaning; present only in a ranking. */
  relevance?: number;
  /** Which repo it's in; present only when ranking across repos. */
  repo?: { id: string; name: string };
}

export type ComponentRole = 'primitive' | 'composite' | 'screen' | 'provider';
export type ComponentKind =
  | 'action' | 'input' | 'display' | 'feedback' | 'navigation' | 'overlay'
  | 'data' | 'content' | 'layout' | 'media' | 'other';

/** Primitives of the same kind — possibly one design-system piece built twice. */
export interface DuplicateGroup {
  kind: ComponentKind;
  components: { id: string; name: string; file: string }[];
}

/** Jev's answer to "which of these fits, and does any?" (server/jev.js rankComponents). */
export interface ComponentRanking {
  exists: number;
  verdict: 'reuse' | 'partial' | 'new';
  considered: number;
  total: number;
  ranked: RepoComponent[];
}

/** One literal design value in a sketch's preview code (server/lint.js). */
export interface LintFinding {
  class: string;
  utility: string;
  property: string;
  value: string;
  kind: 'palette' | 'arbitrary' | 'scale';
  namespace: string;
  /** How many of the repo's tokens of that namespace could stand in for it. */
  candidates: number;
  /** With Jev: whether to replace it, maybe, or keep it. */
  verdict?: 'replace' | 'maybe' | 'keep';
  suggestion?: { token: string; value: string; utility: string; replacement: string; confidence: number } | null;
}

export interface LintResult {
  projectId: string;
  nodeId: string;
  name: string;
  hasCode: boolean;
  classes: number;
  tokens: Record<string, number>;
  findings: LintFinding[];
  truncated: boolean;
  jev: { asked: boolean; model?: string; error?: string };
}

export interface ClassifySketchesResult {
  summary: ClassifySummary & { classifiedPrimitives: number };
  sketches: { id: string; name: string; classification: SketchClassification | null; overlaps: { id: string; name: string; file: string }[] }[];
}

export interface TriageResult {
  summary: { total: number; triaged: number; cached: number; failed: number; error: string | null };
  feedback: { nodeId: string; commentId: string; triage?: CommentTriage }[];
}

export interface ClassifySummary {
  total: number;
  classified: number;
  cached: number;
  failed: number;
  error: string | null;
}

export interface RepoInfo {
  /** owner/repo from the git remote, or the folder name. */
  name: string;
  folder: string;
  root: string;
  branch: string | null;
  remote: string | null;
  isGit: boolean;
}

export interface ComponentIndex {
  root: string;
  repo: RepoInfo;
  scannedAt: string;
  filesScanned: number;
  truncated: boolean;
  count: number;
  components: RepoComponent[];
  /** How many components Jev has classified (answers cached on this machine). */
  classified?: number;
  duplicates?: DuplicateGroup[];
  /** Whether this server has a TYPESAFE_API_KEY, so classify and rank can run. */
  jev?: { available: boolean };
}

export interface CanvasState {
  width: number;
  height: number;
  offsetX: number;
  offsetY: number;
}

export interface DragState {
  isDragging: boolean;
  nodeId: string | null;
  startX: number;
  startY: number;
  initialNodeX: number;
  initialNodeY: number;
}

export interface ResizeState {
  isResizing: boolean;
  nodeId: string | null;
  handle: 'nw' | 'ne' | 'sw' | 'se' | 'n' | 'e' | 's' | 'w' | null;
  startX: number;
  startY: number;
  initialX: number;
  initialY: number;
  initialWidth: number;
  initialHeight: number;
}

export type ThemeMode = 'dark' | 'light';

export interface ProjectContext {
  projectDescription: string;
  targetAudience: string;
  brandName: string;
  brandVoice: string;
  designReferences: string;
  techNotes: string;
  productInfo: string;
}

/**
 * Whether a project's folder in the repo matches the canvas. Computed by the
 * server on every read (see server/export.js), never stored by the client.
 */
export interface RepoSave {
  /** 'canvas' = not in the repo yet; 'saved' = repo copy is current; 'changed' = canvas moved on since. */
  state: 'canvas' | 'saved' | 'changed';
  /** Repo-relative folder the project saves to, once it has been saved. */
  dir: string | null;
  savedAt: string | null;
  /** How many files the last save wrote (README + one per sketch). */
  files: number;
}

export interface Project {
  id: string;
  name: string;
  description: string;
  nodes: ComponentNode[];
  created_at: string;
  updated_at: string;
  /** Freeform notes about the project's design system (tokens, references, conventions) — read by the agent, not consumed by Klose itself. */
  designSystemPrompt?: string;
  projectContext?: ProjectContext;
  repo?: RepoSave;
}

/** A repo as the hub sees it (server/hub.js): where it is, who is working in it, what's on its canvas. */
export interface HubRepo {
  /** Stable id used in /r/<id>/… and /api/repos/<id>/…. */
  id: string;
  root: string;
  /** `root` with the home directory shortened to ~. */
  path: string;
  name: string;
  branch: string | null;
  worktree: boolean;
  /** 'working' = an agent session is busy here; 'idle' = one is open; null = none. */
  agent: 'working' | 'idle' | null;
  /** The session that best describes the repo right now (the busy one, else the latest). */
  session: { name: string | null; status: 'working' | 'idle' } | null;
  sessions: number;
  /** Epoch ms of the last agent activity (or when it was added by hand). */
  lastActive: number;
  hasKlose: boolean;
  files: number;
  sketches: number;
  /** Pending comments across every sketch — feedback the agent hasn't picked up. */
  comments: number;
}

/** The machine at a glance, for the menu bar popover (server/hub.js trayState). */
export interface TrayState {
  /** Picks the menu bar dot: amber for 'feedback', blue for 'working', none otherwise. */
  state: 'feedback' | 'working' | 'idle' | 'none';
  agents: number;
  working: number;
  comments: number;
  repos: HubRepo[];
}

/** First-run setup, as the hub sees it right now (GET /api/setup). */
export interface SetupState {
  claudeCode: { found: boolean; dir: string; sessions: number; working: number; recentFolders: number };
  repos: HubRepo[];
  skills: {
    /** Where machine-wide skills live, e.g. ~/.claude/skills. */
    dir: string;
    installed: boolean;
    list: { name: string; state: 'missing' | 'current' | 'outdated' | 'edited' }[];
  };
  menuBar: { supported: boolean; canBuild: boolean; running: boolean; startAtLogin: boolean };
  onboarding: { completed: boolean; completedAt: string | null };
}

export interface UserSettings {
  themeMode: ThemeMode;
  cssLogicalProperties: boolean;
  rtlDirection: boolean;
}
